spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pagingTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
    open-in-view: true